'use client'
import { GeolocationContextProvider } from '@/Context/GeolocationContext'
import './globals.css'
import { Inter } from 'next/font/google'
import { WeatherContextProvider } from '@/Context/WeatherContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'WeatherHelp',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <head>
        <meta charSet='UTF-8'/>
      </head>
      <body className={inter.className} id='layout'>
        <GeolocationContextProvider>
          <WeatherContextProvider>
          <h1>Weather<strong>Help</strong></h1>
            {children} 
          </WeatherContextProvider>
        </GeolocationContextProvider>
      </body>
    </html>
  )
}
